# Generated by Django 4.0.3 on 2022-04-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cart',
        ),
    ]
